### ISSUE TITLE
Suggested Improvements To Calculator

### ISSUE THREAD

**Issue by musictopia2** [IAmTimCorey/SiteIssues#3]
So far, I am disappointed about the calculator.  Does not have too many options to help a person really see the expected results.
I would suggest the following:
1.  allow a person to adjust the expected earnings even up to 0.
It is possible the best a person can get is volunteer after finishing the course so they would not get any money
2.  allow a person to adjust how long they expect to get the job.
being able to get a job in 6 months is unrealistic.  Obviously, there are usually many more developers applying for the jobs than the jobs that are available.  Obviously, even if somebody has been searching for even 12 months, they don't necessarily have a better chance of getting the job and a prospective employer is not going to favor the one who has been job searching longer.

So would be nice to compare that lets say a person takes 3 years to get the job and they expect to make 20,000 dollars.  Would be nice to see what the calculator would show in that case.

**Comment by TimCorey** [comment]
1. Not getting a job is not an expected outcome. If you don't get a job at the end, something else is the issue.
2. There is not a timeframe on getting a job built into the calculator. It is an apples-to-apples comparison. It assumes that regardless of which route you take, at the end when you are ready to get a job it will take you the same timespan to get that job. Basically, it assumes the outcomes are equal. That is actually not quite true, since my training will give you a better outcome, but I didn't want to weight it towards one or the other.

Regardless of how long it will take you to get a job, the calculator results will be the same. If it takes you three years to get a job, but you finish my course a year earlier than self-taught, you will be in your job a year earlier. Therefore, it will earn you one extra year's worth of salary (in your estimation $20,000, although that is way too low for the US).
