### ISSUE TITLE
Suggestions Site - Mashing Upvote Button

### ISSUE THREAD

**Issue by bobcat251** [IAmTimCorey/SiteIssues#9]
I have seen multiple people (at least 5) asking on your testing and debugging video (lesson 31) about upvote mashing issue. And you have mentioned one fix could be putting "a debounce on the button".
I know the mashing upvote button isn't a big issue, but in case of learning C# it could be helpful for people like me to understand the cause of this issue (I only know it appeared after adding the "session" to certain actions on upvote method in lesson 22) and how to handle it (for example how to do that debounce technic you mentioned).

**Comment by TimCorey** [comment]
The issue is that the user can trigger the button multiple times before the first time actually completes. That means that the second action could start the check, see that a vote hasn't been added yet, and start the process of adding the vote when the first action is already doing the same.

A debounce is just a check to see if you are already doing an action. You could assign a page-wide variable called isUpvoting to be true when you start the method and set it to false when you are done. Then, before you assign the value, you could check to see if it is already true. If it is, you exit the method without doing anything. That would prevent multiple clicks from registering.

Even more simply, you could disable the button until the upvote is registered. That way no click is being registered a second time until the first is complete.
